In [1]:
import pandas as pd
import numpy as np

In [3]:
pip install ucimlrepo

Collecting ucimlrepo
  Downloading ucimlrepo-0.0.7-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: pandas>=1.0.0 in d:\anaconda\lib\site-packages (from ucimlrepo) (2.2.2)
Requirement already satisfied: certifi>=2020.12.5 in d:\anaconda\lib\site-packages (from ucimlrepo) (2026.1.4)
Requirement already satisfied: numpy>=1.26.0 in d:\anaconda\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\anaconda\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\anaconda\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in d:\anaconda\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2023.3)
Requirement already satisfied: six>=1.5 in d:\anaconda\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.16.0)
Downloading ucimlrepo-0.0.7-py3-none-any.whl (8.0 kB)
Installing collected packages: ucimlrepo
Successfully installed ucimlrepo-0.0.7
Note: you may need to restart the kernel to use updated packages.

In [7]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
df = fetch_ucirepo(id=1) 
  
# data (as pandas dataframes) 
X = df.data.features 
y = df.data.targets

{'uci_id': 1, 'name': 'Abalone', 'repository_url': 'https://archive.ics.uci.edu/dataset/1/abalone', 'data_url': 'https://archive.ics.uci.edu/static/public/1/data.csv', 'abstract': 'Predict the age of abalone from physical measurements', 'area': 'Biology', 'tasks': ['Classification', 'Regression'], 'characteristics': ['Tabular'], 'num_instances': 4177, 'num_features': 8, 'feature_types': ['Categorical', 'Integer', 'Real'], 'demographics': [], 'target_col': ['Rings'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1994, 'last_updated': 'Mon Aug 28 2023', 'dataset_doi': '10.24432/C55C7W', 'creators': ['Warwick Nash', 'Tracy Sellers', 'Simon Talbot', 'Andrew Cawthorn', 'Wes Ford'], 'intro_paper': None, 'additional_info': {'summary': 'Predicting the age of abalone from physical measurements.  The age of abalone is determined by cutting the shell through the cone, staining it, and counting the number of rings through a microscope -- a boring and time-consuming task.  Other measurements, which are easier to obtain, are used to predict the age.  Further information, such as weather patterns and location (hence food availability) may be required to solve the problem.\r\n\r\nFrom the original data examples with missing values were removed (the majority having the predicted value missing), and the ranges of the continuous values have been scaled for use with an ANN (by dividing by 200).', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'Given is the attribute name, attribute type, the measurement unit and a brief description.  The number of rings is the value to predict: either as a continuous value or as a classification problem.\r\n\r\nName / Data Type / Measurement Unit / Description\r\n-----------------------------\r\nSex / nominal / -- / M, F, and I (infant)\r\nLength / continuous / mm / Longest shell measurement\r\nDiameter\t/ continuous / mm / perpendicular to length\r\nHeight / continuous / mm / with meat in shell\r\nWhole weight / continuous / grams / whole abalone\r\nShucked weight / continuous\t / grams / weight of meat\r\nViscera weight / continuous / grams / gut weight (after bleeding)\r\nShell weight / continuous / grams / after being dried\r\nRings / integer / -- / +1.5 gives the age in years\r\n\r\nThe readme file contains attribute statistics.', 'citation': None}}
             name     role         type demographic  \
0             Sex  Feature  Categorical        None
1          Length  Feature   Continuous        None
2        Diameter  Feature   Continuous        None
3          Height  Feature   Continuous        None
4    Whole_weight  Feature   Continuous        None
5  Shucked_weight  Feature   Continuous        None
6  Viscera_weight  Feature   Continuous        None
7    Shell_weight  Feature   Continuous        None
8           Rings   Target      Integer        None

                   description  units missing_values
0         M, F, and I (infant)   None             no
1    Longest shell measurement     mm             no
2      perpendicular to length     mm             no
3           with meat in shell     mm             no
4                whole abalone  grams             no
5               weight of meat  grams             no
6  gut weight (after bleeding)  grams             no
7            after being dried  grams             no
8  +1.5 gives the age in years   None             no

In [9]:
X.head()

,Sex,Length,Diameter,Height,Whole_weight,Shucked_weight,Viscera_weight,Shell_weight
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055

In [11]:
y.head()

   Rings
0     15
1      7
2      9
3     10
4      7

In [15]:
y=y+1.5

In [17]:
y.head()

   Rings
0   16.5
1    8.5
2   10.5
3   11.5
4    8.5

In [25]:
#features are shell_weight, length,height
X=X.drop(columns=['Sex','Diameter','Whole_weight','Shucked_weight','Viscera_weight'])
X.head()

   Length  Height  Shell_weight
0   0.455   0.095         0.150
1   0.350   0.090         0.070
2   0.530   0.135         0.210
3   0.440   0.125         0.155
4   0.330   0.080         0.055

In [27]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y,
                                                 test_size=0.2,
                                                random_state=42)

In [33]:
x_train.shape
x_test.shape
y_train.shape
y_test.shape

(836, 1)

In [47]:
mean = np.mean(x_train, axis=0)
std = np.std(x_train, axis=0)
std[std == 0] = 1

# Normalize
x_train= (x_train-mean)/std
x_test= (x_test-mean)/std

In [49]:
def forward(X,w,b):
    """
    computes y_hat = Xw + b
    """
    y_hat =X @ w+ b   # matrix multiplication

    # shapes
    print("Shape of X:", X.shape)
    print("Shape of w:", w.shape)
    print("Shape of b:", np.shape(b))
    print("Shape of y_hat:", y_hat.shape)

    return y_hat

In [51]:
def mse(y, y_hat):
    #MSE
    loss = np.mean((y -y_hat)**2)
    return loss

In [53]:
def grad_w(X,y,y_hat):
    """
    returns gradient with respect to w
    shape must match w
    """
    n=X.shape[0]
    dW=(2/n)*(X.T @ (y_hat-y))
    return dW


def grad_b(y,y_hat):
    """
    returns gradient with respect to b
    """
    n=y.shape[0]
    db=(2/n)*np.sum(y_hat-y)
    return db

In [59]:
n_features = x_train.shape[1]

w= np.random.randn(n_features)*0.01   # small random values
b= 0                                  
# Hyperparameters
learning_rate = 0.01
epochs = 1000
k=100

for epoch in range(epochs):

    
    y_hat =forward(x_train,w,b)

    
    loss =mse(y_train,y_hat)

    
    dW =grad_w(x_train,y_train,y_hat)
    db =grad_b(y_train,y_hat)

    
    w =w- learning_rate*dW
    b =b- learning_rate*db

    if epoch % k == 0:
        print(f"Epoch {epoch}, Loss: {loss}")

Shape of X: (3341, 3)
Shape of w: (3,)
Shape of b: ()
Shape of y_hat: (3341,)

D:\ANACONDA\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

ValueError: Unable to coerce to Series, length must be 3342: given 3

In [63]:
y_test_hat = forward(x_test, w, b)

test_mse = mse(y_test, y_test_hat)
test_mae = np.mean(np.abs(y_test -y_test_hat))

print("Test MSE:",test_mse)
print("Test MAE:",test_mae)

Shape of X: (836, 3)
Shape of w: (3,)
Shape of b: ()
Shape of y_hat: (836,)
Test MSE: nan
Test MAE: nan